### ISSUE TITLE
[docs] Migrate Git for developers

### ISSUE THREAD

**Issue by HuongNV13** [moodle/devdocs#372] opened 2022-09-26 09:48 UTC
### The URL of the page on https://docs.moodle.org/dev/

https://docs.moodle.org/dev/Git_for_developers

### What location would you suggest in the new docs?

I'm thinking about /docs/guides/git

**Comment by bozicm** [comment] 2022-10-04 12:35
Duplicate of #368?

**Comment by andrewnicols** [comment] 2022-10-04 14:13
Thanks @bozicm ,

Closing as duplicate.

**Closed by andrewnicols** 2022-10-04 14:13 UTC
Labels: documentation, migration, needs-triage
